
name: s3-deploy

on:
 [push, pull_request]

jobs:
  s3-Job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{secrets.AWS_PRODUCTION_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: './scglab-status'
          DEST_DIR: 'scglab-status/'
